// Workout Hub — seed content.
// Exercises are the shared library (clip/poster = our generated demo, video = YouTube fallback; icon = kettlebell|dumbbell|treadmill|walk,
// color = accent used in the timer; incline: true adds an incline stepper). Workouts reference
// them by key. Add a workout by appending to WORKOUTS; add an exercise by
// adding a key to EXERCISES. No personal logs live here — those stay on-device.

const EXERCISES = {
  kb_swing: {
    name: 'Kettlebell swings',
    clip: 'media/kb_swing.mp4', poster: 'media/kb_swing.jpg',
    video: 'bDCeXbMJVNs',
    unit: 'kg', step: 4, icon: 'kettlebell', color: '#f59e0b',
    cue: 'Hinge, not squat. Snap the hips, arms are ropes, bell to chest height.',
  },
  db_shoulder_press: {
    name: 'Shoulder press',
    clip: 'media/db_shoulder_press.mp4', poster: 'media/db_shoulder_press.jpg',
    video: '6eDlfTDb7Po',
    unit: 'kg per arm', step: 2.5, icon: 'dumbbell', color: '#a78bfa',
    cue: 'Standing, dumbbells at shoulders, press overhead. Ribs down, no arching.',
  },
  db_incline_press: {
    name: 'Incline chest press',
    clip: 'media/db_incline_press.mp4', poster: 'media/db_incline_press.jpg',
    video: 'c1ZX5ZXMQVk',
    unit: 'kg per arm', step: 2.5, icon: 'dumbbell', color: '#a78bfa',
    cue: 'Bench at ~30°. Elbows ~45° from torso, press up and slightly back.',
  },
  sprint: {
    name: 'Treadmill sprints',
    clip: 'media/sprint.mp4', poster: 'media/sprint.jpg',
    video: 'spg6AXxM3Pk',
    unit: 'kph', step: 0.5, icon: 'treadmill', color: '#38bdf8', incline: true,
    cue: 'Belt keeps running. Hands on rails, hop to the side platforms for the rest, step back on for the next sprint.',
  },
  lat_raise: {
    name: 'Lateral raises',
    clip: 'media/lat_raise.mp4', poster: 'media/lat_raise.jpg',
    video: 'FmouSdWmFxw',
    unit: 'kg per arm', step: 2.5, icon: 'dumbbell', color: '#a78bfa',
    cue: 'Slight elbow bend, raise to shoulder height, lead with the elbows, control the way down.',
  },
  incline_walk: {
    name: 'Incline walk',
    clip: 'media/incline_walk.mp4', poster: 'media/incline_walk.jpg',
    video: 'Ii71nAaRc_8',
    unit: 'kph', step: 0.5, icon: 'walk', color: '#34d399', incline: true,
    cue: 'Hands off the rails. Walk tall, push through the whole foot.',
  },

  // ── expanded library (no demo clips yet; generated on demand) ──
  bb_back_squat: { name: 'Barbell back squat', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Bar on upper back, brace, sit between the hips, knees track over toes, drive up through mid-foot.' },
  bb_front_squat: { name: 'Barbell front squat', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Bar on front delts, elbows high, upright torso, sit straight down.' },
  bb_deadlift: { name: 'Barbell deadlift', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 5, video: '', cue: 'Bar over mid-foot, flat back, push the floor away, lock out hips and knees together.' },
  bb_rdl: { name: 'Barbell Romanian deadlift', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Soft knees, hinge at the hips, bar close to the legs, feel the hamstrings, stand tall.' },
  bb_bench: { name: 'Barbell bench press', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Shoulder blades pinned, bar to lower chest, elbows ~45°, press up and slightly back.' },
  bb_incline_bench: { name: 'Barbell incline bench press', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Bench ~30°, bar to upper chest, elbows tucked, press to lockout.' },
  bb_ohp: { name: 'Barbell overhead press', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Bar at collarbone, brace, press straight up, head through at the top.' },
  bb_row: { name: 'Barbell bent-over row', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Hinge to ~45°, flat back, pull bar to lower ribs, squeeze shoulder blades.' },
  bb_hip_thrust: { name: 'Barbell hip thrust', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 5, video: '', cue: 'Upper back on bench, bar over hips, drive hips up to a straight line, chin tucked.' },
  bb_lunge: { name: 'Barbell lunge', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Long step, back knee toward the floor, front shin vertical, push back to standing.' },
  bb_curl: { name: 'Barbell curl', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Elbows pinned at the sides, curl without swinging, lower slowly.' },
  db_bench: { name: 'Dumbbell bench press', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 2.5, video: '', cue: 'Dumbbells at chest level, press up and in, control the descent.' },
  db_row: { name: 'Dumbbell row', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 2.5, video: '', cue: 'One hand on the bench, flat back, pull the dumbbell to the hip, elbow close.' },
  db_rdl: { name: 'Dumbbell Romanian deadlift', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 2.5, video: '', cue: 'Hinge at the hips with soft knees, dumbbells slide down the thighs, stand tall.' },
  db_goblet_squat: { name: 'Goblet squat', icon: 'dumbbell', color: '#a78bfa', unit: 'kg', step: 2.5, video: '', cue: 'Hold the weight at the chest, elbows inside the knees at the bottom, chest up.' },
  db_lunge: { name: 'Dumbbell lunge', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 2.5, video: '', cue: 'Dumbbells at the sides, long step, front shin vertical, drive back up.' },
  db_bulgarian: { name: 'Bulgarian split squat', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 2.5, video: '', cue: 'Rear foot on a bench, drop straight down, front knee over toes, push through the heel.' },
  db_thruster: { name: 'Dumbbell thruster', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 2.5, video: '', cue: 'Front squat straight into an overhead press, one fluid movement.' },
  db_curl: { name: 'Dumbbell curl', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 1, video: '', cue: 'Elbows at the sides, curl with control, no swinging.' },
  db_hammer_curl: { name: 'Hammer curl', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 1, video: '', cue: 'Neutral grip, palms facing in, curl to the shoulder, lower slowly.' },
  db_tricep_ext: { name: 'Overhead tricep extension', icon: 'dumbbell', color: '#a78bfa', unit: 'kg', step: 2.5, video: '', cue: 'One dumbbell overhead with both hands, lower behind the head, elbows pointing forward.' },
  db_front_raise: { name: 'Front raise', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 1, video: '', cue: 'Slight elbow bend, raise to shoulder height, lower under control.' },
  db_rear_delt_fly: { name: 'Rear delt fly', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 1, video: '', cue: 'Hinge forward, arms out to the sides leading with the elbows, squeeze the upper back.' },
  db_step_up: { name: 'Dumbbell step-up', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 2.5, video: '', cue: 'Whole foot on the box, drive through the front leg, no push from the back foot.' },
  db_floor_press: { name: 'Dumbbell floor press', icon: 'dumbbell', color: '#a78bfa', unit: 'kg per arm', step: 2.5, video: '', cue: 'Lying on the floor, elbows touch down each rep, press to lockout.' },
  kb_goblet_squat: { name: 'Kettlebell goblet squat', icon: 'kettlebell', color: '#f59e0b', unit: 'kg', step: 4, video: '', cue: 'Bell at the chest, elbows inside the knees, chest up, drive through the heels.' },
  kb_clean: { name: 'Kettlebell clean', icon: 'kettlebell', color: '#f59e0b', unit: 'kg', step: 4, video: '', cue: 'Swing the bell up and rotate it around the wrist into the rack, no banging the forearm.' },
  kb_press: { name: 'Kettlebell press', icon: 'kettlebell', color: '#f59e0b', unit: 'kg', step: 4, video: '', cue: 'From the rack, press straight up, lock out, lower under control.' },
  kb_snatch: { name: 'Kettlebell snatch', icon: 'kettlebell', color: '#f59e0b', unit: 'kg', step: 4, video: '', cue: 'One swing into a punch-through overhead, bell lands softly on the wrist.' },
  kb_deadlift: { name: 'Kettlebell deadlift', icon: 'kettlebell', color: '#f59e0b', unit: 'kg', step: 4, video: '', cue: 'Bell between the feet, hinge, flat back, stand tall.' },
  kb_turkish_getup: { name: 'Turkish get-up', icon: 'kettlebell', color: '#f59e0b', unit: 'kg', step: 4, video: '', cue: 'Bell locked out overhead the whole way, roll to elbow, hand, bridge, sweep, stand. Slow.' },
  kb_row: { name: 'Kettlebell row', icon: 'kettlebell', color: '#f59e0b', unit: 'kg', step: 4, video: '', cue: 'Hinge, pull the bell to the hip, elbow close to the body.' },
  bw_pushup: { name: 'Push-up', icon: 'body', color: '#fbbf24', unit: 'reps', step: 1, video: '', cue: 'Hands under shoulders, body in a straight line, chest to the floor, elbows ~45°.' },
  bw_pullup: { name: 'Pull-up', icon: 'body', color: '#fbbf24', unit: 'reps', step: 1, video: '', cue: 'Dead hang, pull chest to the bar, control the way down.' },
  bw_chinup: { name: 'Chin-up', icon: 'body', color: '#fbbf24', unit: 'reps', step: 1, video: '', cue: 'Underhand grip, chin over the bar, lower slowly.' },
  bw_dip: { name: 'Dip', icon: 'body', color: '#fbbf24', unit: 'reps', step: 1, video: '', cue: 'Lean slightly forward, lower until upper arms are parallel, press up.' },
  bw_squat: { name: 'Bodyweight squat', icon: 'body', color: '#fbbf24', unit: 'reps', step: 1, video: '', cue: 'Feet shoulder-width, sit back and down, chest up, drive through the heels.' },
  bw_lunge: { name: 'Walking lunge', icon: 'body', color: '#fbbf24', unit: 'reps', step: 1, video: '', cue: 'Step long, back knee toward the floor, alternate legs.' },
  bw_burpee: { name: 'Burpee', icon: 'body', color: '#fbbf24', unit: 'reps', step: 1, video: '', cue: 'Drop to the floor, chest down, jump the feet in, jump up.' },
  bw_plank: { name: 'Plank', icon: 'core', color: '#c084fc', unit: 's', step: 10, video: '', cue: 'Forearms down, body in a straight line, squeeze glutes, breathe.' },
  bw_side_plank: { name: 'Side plank', icon: 'core', color: '#c084fc', unit: 's', step: 10, video: '', cue: 'Elbow under shoulder, hips high, straight line head to feet.' },
  bw_mountain_climber: { name: 'Mountain climbers', icon: 'core', color: '#c084fc', unit: 'reps', step: 2, video: '', cue: 'Hands under shoulders, drive knees to chest alternately, hips level.' },
  bw_situp: { name: 'Sit-up', icon: 'core', color: '#c084fc', unit: 'reps', step: 1, video: '', cue: 'Feet flat, curl up through the spine, lower with control.' },
  bw_leg_raise: { name: 'Hanging leg raise', icon: 'core', color: '#c084fc', unit: 'reps', step: 1, video: '', cue: 'Hang, raise straight legs to parallel or higher, no swinging.' },
  bw_hip_bridge: { name: 'Glute bridge', icon: 'body', color: '#fbbf24', unit: 'reps', step: 1, video: '', cue: 'Feet flat, drive hips to the ceiling, squeeze at the top.' },
  bw_jump_squat: { name: 'Jump squat', icon: 'body', color: '#fbbf24', unit: 'reps', step: 1, video: '', cue: 'Squat, explode up, land softly back into the squat.' },
  bw_box_jump: { name: 'Box jump', icon: 'body', color: '#fbbf24', unit: 'reps', step: 1, video: '', cue: 'Swing the arms, jump, land softly on the whole foot, step down.' },
  bw_jumping_jack: { name: 'Jumping jacks', icon: 'body', color: '#fbbf24', unit: 'reps', step: 5, video: '', cue: 'Arms overhead as the feet go wide, snap back together.' },
  cable_lat_pulldown: { name: 'Lat pulldown', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Lean back slightly, pull the bar to the upper chest, elbows down and back.' },
  cable_row: { name: 'Seated cable row', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Chest up, pull the handle to the stomach, squeeze the shoulder blades.' },
  cable_face_pull: { name: 'Face pull', icon: 'band', color: '#f472b6', unit: 'kg', step: 2.5, video: '', cue: 'Rope at face height, pull toward the eyes, elbows high, squeeze the rear delts.' },
  cable_tricep_pushdown: { name: 'Tricep pushdown', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Elbows pinned, push down to lockout, control the way up.' },
  machine_leg_press: { name: 'Leg press', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 5, video: '', cue: 'Feet shoulder-width on the platform, lower until knees ~90°, press without locking hard.' },
  machine_leg_curl: { name: 'Leg curl', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Curl the pad toward the glutes, pause, lower slowly.' },
  machine_leg_ext: { name: 'Leg extension', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Extend to straight, squeeze the quads, lower under control.' },
  machine_chest_press: { name: 'Chest press machine', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Handles at chest height, press to lockout, control the return.' },
  machine_shoulder_press: { name: 'Shoulder press machine', icon: 'barbell', color: '#fb7185', unit: 'kg', step: 2.5, video: '', cue: 'Press overhead, don\'t lock out hard, lower to ear level.' },
  cardio_rower: { name: 'Rowing machine', icon: 'rower', color: '#60a5fa', unit: 'm', step: 100, video: '', cue: 'Legs, then body, then arms on the drive; arms, body, legs on the way back.' },
  cardio_bike: { name: 'Stationary bike', icon: 'bike', color: '#22d3ee', unit: 'kph', step: 1, video: '', cue: 'Seat at hip height, smooth cadence, hands light on the bars.' },
  cardio_assault_bike: { name: 'Assault bike', icon: 'bike', color: '#22d3ee', unit: 'cal', step: 5, video: '', cue: 'Push and pull with the arms, drive with the legs, keep the cadence up.' },
  cardio_stairmaster: { name: 'Stair climber', icon: 'walk', color: '#34d399', unit: 'reps', step: 1, video: '', cue: 'Whole foot on each step, hands light, stand tall.' },
  cardio_cross_trainer: { name: 'Cross trainer', icon: 'walk', color: '#34d399', unit: 'kph', step: 0.5, video: '', cue: 'Push through the heels, use the handles, keep an upright posture.' },
  cardio_skierg: { name: 'Ski erg', icon: 'rower', color: '#60a5fa', unit: 'm', step: 100, video: '', cue: 'Reach high, drive the handles down with the hips and arms together.' },
  cardio_jump_rope: { name: 'Skipping', icon: 'body', color: '#fbbf24', unit: 's', step: 15, video: '', cue: 'Light on the toes, wrists turn the rope, small jumps.' },
  cardio_run: { name: 'Run', icon: 'run', color: '#fb923c', unit: 'kph', step: 0.5, video: '', cue: 'Relaxed shoulders, quick light steps, land under the hips.' },
  cardio_swim: { name: 'Swim', icon: 'swim', color: '#38bdf8', unit: 'm', step: 25, video: '', cue: 'Long strokes, steady breathing, count lengths.' },
};

// Block types:
//   interval — rounds × (each exercise: work_s on, rest_s off)
//   steady   — segments × repeat, each segment is timed at a speed/incline
const WORKOUTS = [
  {
    id: 'priyanka-swings-incline-press-sprints',
    title: 'Swings, incline press & sprints',
    creator: 'Priyanka',
    created: '2026-09-02',
    level: 'Hard',
    tags: ['HIIT', 'Kettlebell', 'Treadmill'],
    blocks: [
      { name: 'Swings + incline press', type: 'interval', work_s: 30, rest_s: 30, rounds: 8,
        exercises: [ { ex: 'kb_swing', target: 28 }, { ex: 'db_incline_press', target: 15 } ] },
      { name: 'Sprints', type: 'interval', work_s: 30, rest_s: 30, rounds: 8,
        exercises: [ { ex: 'sprint', target: 14.5 } ] },
      { name: 'Swings + lateral raises', type: 'interval', work_s: 30, rest_s: 30, rounds: 4,
        exercises: [ { ex: 'kb_swing', target: 28 }, { ex: 'lat_raise', target: 7.5 } ] },
      { name: 'Incline walk', type: 'steady', ex: 'incline_walk', incline: 6, repeat: 2,
        segments: [ { s: 120, speed: 6 }, { s: 180, speed: 9 } ] },
    ],
  },
  {
    id: 'priyanka-swings-press-sprints',
    title: 'Swings, shoulder press & sprints',
    creator: 'Priyanka',
    created: '2026-08-23',
    level: 'Hard',
    tags: ['HIIT', 'Kettlebell', 'Treadmill'],
    blocks: [
      { name: 'Swings + shoulder press', type: 'interval', work_s: 30, rest_s: 30, rounds: 8,
        exercises: [ { ex: 'kb_swing', target: 28 }, { ex: 'db_shoulder_press', target: 15 } ] },
      { name: 'Sprints', type: 'interval', work_s: 30, rest_s: 30, rounds: 8,
        exercises: [ { ex: 'sprint', target: 14.5 } ] },
      { name: 'Swings', type: 'interval', work_s: 30, rest_s: 30, rounds: 8,
        exercises: [ { ex: 'kb_swing', target: 24 } ] },
      { name: 'Lateral raises', type: 'interval', work_s: 30, rest_s: 30, rounds: 2,
        exercises: [ { ex: 'lat_raise', target: 7.5 } ] },
      { name: 'Incline walk', type: 'steady', ex: 'incline_walk', incline: 6, repeat: 3,
        segments: [ { s: 120, speed: 6 }, { s: 180, speed: 9 } ] },
    ],
  },
  {
    id: 'nick-long-incline-walk',
    title: 'Long incline walk',
    creator: 'Nick',
    created: '2026-09-03',
    level: 'Easy',
    tags: ['Treadmill', 'Walk', 'Steady'],
    blocks: [
      // 75 min, ~4.4 km → ~3.5 kph. Incline is a placeholder (set what the treadmill was on).
      { name: 'Incline walk', type: 'steady', ex: 'incline_walk', incline: 10, repeat: 1,
        segments: [ { s: 4500, speed: 3.5 } ] },
    ],
  },
];
