#!/usr/bin/env node
// Generates supabase/seed.sql from data.js so seed content lives in one place.
// Usage (from workout-hub/):  node tools/seed.mjs > supabase/seed.sql
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const src = readFileSync(new URL('../data.js', import.meta.url), 'utf8');
const ctx = {};
vm.runInNewContext(src + '\nthis.EXERCISES = EXERCISES; this.WORKOUTS = WORKOUTS;', ctx);
const q = v => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const t = s => `'${String(s).replace(/'/g, "''")}'`;

const lines = ['-- generated by tools/seed.mjs — do not edit by hand', 'begin;'];
for (const [key, e] of Object.entries(ctx.EXERCISES))
  lines.push(`insert into public.exercises (key, owner, public, data) values (${t(key)}, null, true, ${q(e)}) on conflict (key) do update set data = excluded.data;`);
for (const w of ctx.WORKOUTS)
  lines.push(`insert into public.workouts (id, owner, creator, title, public, data) values (${t(w.id)}, null, ${t(w.creator)}, ${t(w.title)}, true, ${q(w)}) on conflict (id) do update set data = excluded.data, title = excluded.title, creator = excluded.creator;`);
lines.push('commit;');
process.stdout.write(lines.join('\n') + '\n');
