// Generated from ../../../../workout-hub/data.js by tools/port-library.mjs. Edit there, then re-run.
import type { ExerciseRef } from '@/features/runsheet/model';

export type ExerciseGroup = "kettlebell" | "dumbbell" | "treadmill" | "walk" | "barbell" | "body" | "core" | "band" | "rower" | "bike" | "run" | "swim";

export interface LibraryExercise extends ExerciseRef {
  group: ExerciseGroup;
  cue: string;
}

export const GROUP_LABEL: Record<ExerciseGroup, string> = {
  "kettlebell": "Kettlebell",
  "dumbbell": "Dumbbell",
  "treadmill": "Treadmill",
  "walk": "Walking & stairs",
  "barbell": "Barbell & machines",
  "body": "Bodyweight",
  "core": "Core",
  "band": "Cable & band",
  "rower": "Rower & ski",
  "bike": "Bike",
  "run": "Running",
  "swim": "Swim"
};

export const LIBRARY: Record<string, LibraryExercise> = {
  "kb_swing": {"key":"kb_swing","name":"Kettlebell swings","unit":"kg","step":4,"group":"kettlebell","cue":"Hinge, not squat. Snap the hips, arms are ropes, bell to chest height.","clip":"media/kb_swing.mp4","poster":"media/kb_swing.jpg"},
  "db_shoulder_press": {"key":"db_shoulder_press","name":"Shoulder press","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"Standing, dumbbells at shoulders, press overhead. Ribs down, no arching.","clip":"media/db_shoulder_press.mp4","poster":"media/db_shoulder_press.jpg"},
  "db_incline_press": {"key":"db_incline_press","name":"Incline chest press","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"Bench at ~30°. Elbows ~45° from torso, press up and slightly back.","clip":"media/db_incline_press.mp4","poster":"media/db_incline_press.jpg"},
  "sprint": {"key":"sprint","name":"Treadmill sprints","unit":"kph","step":0.5,"group":"treadmill","cue":"Belt keeps running. Hands on rails, hop to the side platforms for the rest, step back on for the next sprint.","clip":"media/sprint.mp4","poster":"media/sprint.jpg"},
  "lat_raise": {"key":"lat_raise","name":"Lateral raises","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"Slight elbow bend, raise to shoulder height, lead with the elbows, control the way down.","clip":"media/lat_raise.mp4","poster":"media/lat_raise.jpg"},
  "incline_walk": {"key":"incline_walk","name":"Incline walk","unit":"kph","step":0.5,"group":"walk","cue":"Hands off the rails. Walk tall, push through the whole foot.","clip":"media/incline_walk.mp4","poster":"media/incline_walk.jpg"},
  "bb_back_squat": {"key":"bb_back_squat","name":"Barbell back squat","unit":"kg","step":2.5,"group":"barbell","cue":"Bar on upper back, brace, sit between the hips, knees track over toes, drive up through mid-foot.","poster":"media/bb_back_squat.jpg"},
  "bb_front_squat": {"key":"bb_front_squat","name":"Barbell front squat","unit":"kg","step":2.5,"group":"barbell","cue":"Bar on front delts, elbows high, upright torso, sit straight down.","poster":"media/bb_front_squat.jpg"},
  "bb_deadlift": {"key":"bb_deadlift","name":"Barbell deadlift","unit":"kg","step":5,"group":"barbell","cue":"Bar over mid-foot, flat back, push the floor away, lock out hips and knees together.","poster":"media/bb_deadlift.jpg"},
  "bb_rdl": {"key":"bb_rdl","name":"Barbell Romanian deadlift","unit":"kg","step":2.5,"group":"barbell","cue":"Soft knees, hinge at the hips, bar close to the legs, feel the hamstrings, stand tall.","poster":"media/bb_rdl.jpg"},
  "bb_bench": {"key":"bb_bench","name":"Barbell bench press","unit":"kg","step":2.5,"group":"barbell","cue":"Shoulder blades pinned, bar to lower chest, elbows ~45°, press up and slightly back.","poster":"media/bb_bench.jpg"},
  "bb_incline_bench": {"key":"bb_incline_bench","name":"Barbell incline bench press","unit":"kg","step":2.5,"group":"barbell","cue":"Bench ~30°, bar to upper chest, elbows tucked, press to lockout.","poster":"media/bb_incline_bench.jpg"},
  "bb_ohp": {"key":"bb_ohp","name":"Barbell overhead press","unit":"kg","step":2.5,"group":"barbell","cue":"Bar at collarbone, brace, press straight up, head through at the top.","poster":"media/bb_ohp.jpg"},
  "bb_row": {"key":"bb_row","name":"Barbell bent-over row","unit":"kg","step":2.5,"group":"barbell","cue":"Hinge to ~45°, flat back, pull bar to lower ribs, squeeze shoulder blades.","poster":"media/bb_row.jpg"},
  "bb_hip_thrust": {"key":"bb_hip_thrust","name":"Barbell hip thrust","unit":"kg","step":5,"group":"barbell","cue":"Upper back on bench, bar over hips, drive hips up to a straight line, chin tucked.","poster":"media/bb_hip_thrust.jpg"},
  "bb_lunge": {"key":"bb_lunge","name":"Barbell lunge","unit":"kg","step":2.5,"group":"barbell","cue":"Long step, back knee toward the floor, front shin vertical, push back to standing.","poster":"media/bb_lunge.jpg"},
  "bb_curl": {"key":"bb_curl","name":"Barbell curl","unit":"kg","step":2.5,"group":"barbell","cue":"Elbows pinned at the sides, curl without swinging, lower slowly.","poster":"media/bb_curl.jpg"},
  "db_bench": {"key":"db_bench","name":"Dumbbell bench press","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"Dumbbells at chest level, press up and in, control the descent.","poster":"media/db_bench.jpg"},
  "db_row": {"key":"db_row","name":"Dumbbell row","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"One hand on the bench, flat back, pull the dumbbell to the hip, elbow close.","poster":"media/db_row.jpg"},
  "db_rdl": {"key":"db_rdl","name":"Dumbbell Romanian deadlift","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"Hinge at the hips with soft knees, dumbbells slide down the thighs, stand tall.","poster":"media/db_rdl.jpg"},
  "db_goblet_squat": {"key":"db_goblet_squat","name":"Goblet squat","unit":"kg","step":2.5,"group":"dumbbell","cue":"Hold the weight at the chest, elbows inside the knees at the bottom, chest up.","poster":"media/db_goblet_squat.jpg"},
  "db_lunge": {"key":"db_lunge","name":"Dumbbell lunge","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"Dumbbells at the sides, long step, front shin vertical, drive back up.","poster":"media/db_lunge.jpg"},
  "db_bulgarian": {"key":"db_bulgarian","name":"Bulgarian split squat","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"Rear foot on a bench, drop straight down, front knee over toes, push through the heel.","poster":"media/db_bulgarian.jpg"},
  "db_thruster": {"key":"db_thruster","name":"Dumbbell thruster","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"Front squat straight into an overhead press, one fluid movement.","poster":"media/db_thruster.jpg"},
  "db_curl": {"key":"db_curl","name":"Dumbbell curl","unit":"kg per arm","step":1,"group":"dumbbell","cue":"Elbows at the sides, curl with control, no swinging.","poster":"media/db_curl.jpg"},
  "db_hammer_curl": {"key":"db_hammer_curl","name":"Hammer curl","unit":"kg per arm","step":1,"group":"dumbbell","cue":"Neutral grip, palms facing in, curl to the shoulder, lower slowly.","poster":"media/db_hammer_curl.jpg"},
  "db_tricep_ext": {"key":"db_tricep_ext","name":"Overhead tricep extension","unit":"kg","step":2.5,"group":"dumbbell","cue":"One dumbbell overhead with both hands, lower behind the head, elbows pointing forward.","poster":"media/db_tricep_ext.jpg"},
  "db_front_raise": {"key":"db_front_raise","name":"Front raise","unit":"kg per arm","step":1,"group":"dumbbell","cue":"Slight elbow bend, raise to shoulder height, lower under control.","poster":"media/db_front_raise.jpg"},
  "db_rear_delt_fly": {"key":"db_rear_delt_fly","name":"Rear delt fly","unit":"kg per arm","step":1,"group":"dumbbell","cue":"Hinge forward, arms out to the sides leading with the elbows, squeeze the upper back.","poster":"media/db_rear_delt_fly.jpg"},
  "db_step_up": {"key":"db_step_up","name":"Dumbbell step-up","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"Whole foot on the box, drive through the front leg, no push from the back foot.","poster":"media/db_step_up.jpg"},
  "db_floor_press": {"key":"db_floor_press","name":"Dumbbell floor press","unit":"kg per arm","step":2.5,"group":"dumbbell","cue":"Lying on the floor, elbows touch down each rep, press to lockout.","poster":"media/db_floor_press.jpg"},
  "kb_goblet_squat": {"key":"kb_goblet_squat","name":"Kettlebell goblet squat","unit":"kg","step":4,"group":"kettlebell","cue":"Bell at the chest, elbows inside the knees, chest up, drive through the heels.","poster":"media/kb_goblet_squat.jpg"},
  "kb_clean": {"key":"kb_clean","name":"Kettlebell clean","unit":"kg","step":4,"group":"kettlebell","cue":"Swing the bell up and rotate it around the wrist into the rack, no banging the forearm.","poster":"media/kb_clean.jpg"},
  "kb_press": {"key":"kb_press","name":"Kettlebell press","unit":"kg","step":4,"group":"kettlebell","cue":"From the rack, press straight up, lock out, lower under control.","poster":"media/kb_press.jpg"},
  "kb_snatch": {"key":"kb_snatch","name":"Kettlebell snatch","unit":"kg","step":4,"group":"kettlebell","cue":"One swing into a punch-through overhead, bell lands softly on the wrist.","poster":"media/kb_snatch.jpg"},
  "kb_deadlift": {"key":"kb_deadlift","name":"Kettlebell deadlift","unit":"kg","step":4,"group":"kettlebell","cue":"Bell between the feet, hinge, flat back, stand tall.","poster":"media/kb_deadlift.jpg"},
  "kb_turkish_getup": {"key":"kb_turkish_getup","name":"Turkish get-up","unit":"kg","step":4,"group":"kettlebell","cue":"Bell locked out overhead the whole way, roll to elbow, hand, bridge, sweep, stand. Slow.","poster":"media/kb_turkish_getup.jpg"},
  "kb_row": {"key":"kb_row","name":"Kettlebell row","unit":"kg","step":4,"group":"kettlebell","cue":"Hinge, pull the bell to the hip, elbow close to the body.","poster":"media/kb_row.jpg"},
  "bw_pushup": {"key":"bw_pushup","name":"Push-up","unit":"reps","step":1,"group":"body","cue":"Hands under shoulders, body in a straight line, chest to the floor, elbows ~45°.","poster":"media/bw_pushup.jpg"},
  "bw_pullup": {"key":"bw_pullup","name":"Pull-up","unit":"reps","step":1,"group":"body","cue":"Dead hang, pull chest to the bar, control the way down.","poster":"media/bw_pullup.jpg"},
  "bw_chinup": {"key":"bw_chinup","name":"Chin-up","unit":"reps","step":1,"group":"body","cue":"Underhand grip, chin over the bar, lower slowly.","poster":"media/bw_chinup.jpg"},
  "bw_dip": {"key":"bw_dip","name":"Dip","unit":"reps","step":1,"group":"body","cue":"Lean slightly forward, lower until upper arms are parallel, press up.","poster":"media/bw_dip.jpg"},
  "bw_squat": {"key":"bw_squat","name":"Bodyweight squat","unit":"reps","step":1,"group":"body","cue":"Feet shoulder-width, sit back and down, chest up, drive through the heels.","poster":"media/bw_squat.jpg"},
  "bw_lunge": {"key":"bw_lunge","name":"Walking lunge","unit":"reps","step":1,"group":"body","cue":"Step long, back knee toward the floor, alternate legs.","poster":"media/bw_lunge.jpg"},
  "bw_burpee": {"key":"bw_burpee","name":"Burpee","unit":"reps","step":1,"group":"body","cue":"Drop to the floor, chest down, jump the feet in, jump up.","poster":"media/bw_burpee.jpg"},
  "bw_plank": {"key":"bw_plank","name":"Plank","unit":"s","step":10,"group":"core","cue":"Forearms down, body in a straight line, squeeze glutes, breathe.","poster":"media/bw_plank.jpg"},
  "bw_side_plank": {"key":"bw_side_plank","name":"Side plank","unit":"s","step":10,"group":"core","cue":"Elbow under shoulder, hips high, straight line head to feet.","poster":"media/bw_side_plank.jpg"},
  "bw_mountain_climber": {"key":"bw_mountain_climber","name":"Mountain climbers","unit":"reps","step":2,"group":"core","cue":"Hands under shoulders, drive knees to chest alternately, hips level.","poster":"media/bw_mountain_climber.jpg"},
  "bw_situp": {"key":"bw_situp","name":"Sit-up","unit":"reps","step":1,"group":"core","cue":"Feet flat, curl up through the spine, lower with control.","poster":"media/bw_situp.jpg"},
  "bw_leg_raise": {"key":"bw_leg_raise","name":"Hanging leg raise","unit":"reps","step":1,"group":"core","cue":"Hang, raise straight legs to parallel or higher, no swinging.","poster":"media/bw_leg_raise.jpg"},
  "bw_hip_bridge": {"key":"bw_hip_bridge","name":"Glute bridge","unit":"reps","step":1,"group":"body","cue":"Feet flat, drive hips to the ceiling, squeeze at the top.","poster":"media/bw_hip_bridge.jpg"},
  "bw_jump_squat": {"key":"bw_jump_squat","name":"Jump squat","unit":"reps","step":1,"group":"body","cue":"Squat, explode up, land softly back into the squat.","poster":"media/bw_jump_squat.jpg"},
  "bw_box_jump": {"key":"bw_box_jump","name":"Box jump","unit":"reps","step":1,"group":"body","cue":"Swing the arms, jump, land softly on the whole foot, step down.","poster":"media/bw_box_jump.jpg"},
  "bw_jumping_jack": {"key":"bw_jumping_jack","name":"Jumping jacks","unit":"reps","step":5,"group":"body","cue":"Arms overhead as the feet go wide, snap back together.","poster":"media/bw_jumping_jack.jpg"},
  "cable_lat_pulldown": {"key":"cable_lat_pulldown","name":"Lat pulldown","unit":"kg","step":2.5,"group":"barbell","cue":"Lean back slightly, pull the bar to the upper chest, elbows down and back.","poster":"media/cable_lat_pulldown.jpg"},
  "cable_row": {"key":"cable_row","name":"Seated cable row","unit":"kg","step":2.5,"group":"barbell","cue":"Chest up, pull the handle to the stomach, squeeze the shoulder blades.","poster":"media/cable_row.jpg"},
  "cable_face_pull": {"key":"cable_face_pull","name":"Face pull","unit":"kg","step":2.5,"group":"band","cue":"Rope at face height, pull toward the eyes, elbows high, squeeze the rear delts.","poster":"media/cable_face_pull.jpg"},
  "cable_tricep_pushdown": {"key":"cable_tricep_pushdown","name":"Tricep pushdown","unit":"kg","step":2.5,"group":"barbell","cue":"Elbows pinned, push down to lockout, control the way up.","poster":"media/cable_tricep_pushdown.jpg"},
  "machine_leg_press": {"key":"machine_leg_press","name":"Leg press","unit":"kg","step":5,"group":"barbell","cue":"Feet shoulder-width on the platform, lower until knees ~90°, press without locking hard.","poster":"media/machine_leg_press.jpg"},
  "machine_leg_curl": {"key":"machine_leg_curl","name":"Leg curl","unit":"kg","step":2.5,"group":"barbell","cue":"Curl the pad toward the glutes, pause, lower slowly.","poster":"media/machine_leg_curl.jpg"},
  "machine_leg_ext": {"key":"machine_leg_ext","name":"Leg extension","unit":"kg","step":2.5,"group":"barbell","cue":"Extend to straight, squeeze the quads, lower under control.","poster":"media/machine_leg_ext.jpg"},
  "machine_chest_press": {"key":"machine_chest_press","name":"Chest press machine","unit":"kg","step":2.5,"group":"barbell","cue":"Handles at chest height, press to lockout, control the return.","poster":"media/machine_chest_press.jpg"},
  "machine_shoulder_press": {"key":"machine_shoulder_press","name":"Shoulder press machine","unit":"kg","step":2.5,"group":"barbell","cue":"Press overhead, don't lock out hard, lower to ear level.","poster":"media/machine_shoulder_press.jpg"},
  "cardio_rower": {"key":"cardio_rower","name":"Rowing machine","unit":"m","step":100,"group":"rower","cue":"Legs, then body, then arms on the drive; arms, body, legs on the way back.","poster":"media/cardio_rower.jpg"},
  "cardio_bike": {"key":"cardio_bike","name":"Stationary bike","unit":"kph","step":1,"group":"bike","cue":"Seat at hip height, smooth cadence, hands light on the bars.","poster":"media/cardio_bike.jpg"},
  "cardio_assault_bike": {"key":"cardio_assault_bike","name":"Assault bike","unit":"cal","step":5,"group":"bike","cue":"Push and pull with the arms, drive with the legs, keep the cadence up.","poster":"media/cardio_assault_bike.jpg"},
  "cardio_stairmaster": {"key":"cardio_stairmaster","name":"Stair climber","unit":"reps","step":1,"group":"walk","cue":"Whole foot on each step, hands light, stand tall.","poster":"media/cardio_stairmaster.jpg"},
  "cardio_cross_trainer": {"key":"cardio_cross_trainer","name":"Cross trainer","unit":"kph","step":0.5,"group":"walk","cue":"Push through the heels, use the handles, keep an upright posture.","poster":"media/cardio_cross_trainer.jpg"},
  "cardio_skierg": {"key":"cardio_skierg","name":"Ski erg","unit":"m","step":100,"group":"rower","cue":"Reach high, drive the handles down with the hips and arms together.","poster":"media/cardio_skierg.jpg"},
  "cardio_jump_rope": {"key":"cardio_jump_rope","name":"Skipping","unit":"s","step":15,"group":"body","cue":"Light on the toes, wrists turn the rope, small jumps.","poster":"media/cardio_jump_rope.jpg"},
  "cardio_run": {"key":"cardio_run","name":"Run","unit":"kph","step":0.5,"group":"run","cue":"Relaxed shoulders, quick light steps, land under the hips.","poster":"media/cardio_run.jpg"},
  "cardio_swim": {"key":"cardio_swim","name":"Swim","unit":"m","step":25,"group":"swim","cue":"Long strokes, steady breathing, count lengths.","poster":"media/cardio_swim.jpg"},
};

export const exerciseRef = (key: string): ExerciseRef => LIBRARY[key] ?? { key, name: key, unit: 'kg', step: 2.5 };
